# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.kernelParams = ["nohibernate" "zfs.zfs_arc_max=12884901888"];
  boot.kernelPackages = config.boot.zfs.package.latestCompatibleLinuxPackages;
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/root";
      fsType = "zfs";
    };

  boot.initrd.luks.devices."crypt" = 
   {device = "/dev/disk/by-uuid/809605c2-f209-4b35-adc3-da2590d9b1fd";
    preLVM = true;
   };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D682-66E8";
      fsType = "vfat";
      options = ["noatime"];
    };

  fileSystems."/nix" =
    { device = "rpool/nix";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    { device = "rpool/persist";
      fsType = "zfs";
      options = ["noatime"];
      neededForBoot = true;
    };

  swapDevices = [ ];


  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
